# Generated by Django 6.0.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
